'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("EEICA.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AdobeAcrobatReader5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AdobeAcrobatReader5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property backgroundTrans() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("backgroundTrans", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPDATE V
        '''SET update_err=&apos;To Remove&apos;
        '''FROM
        '''(
        '''SELECT 
        '''[tbl_id],update_err
        '''FROM [tbl_Update_MileStone]
        '''INNER JOIN [vCblParProductionTotal_Vendor]
        '''ON [tbl_Update_MileStone].tag=[vCblParProductionTotal_Vendor].TAG
        '''WHERE [tbl_Update_MileStone].update_user=&apos;userxxx&apos;
        '''AND [tbl_Update_MileStone].item_type IN (11,31,101)
        '''AND [ms_3]=Percentage
        ''') AS V.
        '''</summary>
        Friend ReadOnly Property CleanProTable() As String
            Get
                Return ResourceManager.GetString("CleanProTable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE TABLE [dbo].[getProjectElements(&apos;10031&apos;)](
        '''	[ProjectCode] [nvarchar](255) NULL,
        '''	[Area] [nvarchar](255) NULL,
        '''	[Unit] [nvarchar](255) NULL,
        '''	[Module] [nvarchar](255) NULL,
        '''	[System] [nvarchar](255) NULL,
        '''	[SubSystem] [nvarchar](255) NULL,
        '''	[Group] [nvarchar](255) NULL,
        '''	[Item] [nvarchar](255) NULL,
        '''	[ElementType] [nvarchar](255) NULL,
        '''	[ElementCode] [nvarchar](255) NULL,
        '''	[Name] [nvarchar](255) NULL,
        '''	[Discipline] [nvarchar](255) NULL,
        '''	[Type] [nvarchar](255) NULL,
        '''	[Class] [nvarchar](2 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CreateElement() As String
            Get
                Return ResourceManager.GetString("CreateElement", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE TABLE [dbo].[getProjectGroups(&apos;10031&apos;)](
        '''	[Area] [nvarchar](255) NULL,
        '''	[Unit] [nvarchar](255) NULL,
        '''	[System] [nvarchar](255) NULL,
        '''	[SubSystem] [nvarchar](255) NULL,
        '''	[Module] [nvarchar](255) NULL,
        '''	[GroupID] [nvarchar](255) NULL,
        '''	[GroupName] [nvarchar](255) NULL,
        '''	[Revision] [nvarchar](255) NULL,
        '''	[Discipline] [nvarchar](255) NULL,
        '''	[Type] [nvarchar](255) NULL,
        '''	[Class] [nvarchar](255) NULL,
        '''	[Folder] [bit] NOT NULL,
        '''	[Subcontractor] [nvarchar](255) NULL,
        '''	[Weight] [float] NULL,
        '''	[ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CreateGroups() As String
            Get
                Return ResourceManager.GetString("CreateGroups", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE TABLE [dbo].[getProjectItems(&apos;10031&apos;)](
        '''	[Area] [nvarchar](255) NULL,
        '''	[Unit] [nvarchar](255) NULL,
        '''	[System] [nvarchar](255) NULL,
        '''	[SubSystem] [nvarchar](255) NULL,
        '''	[Module] [nvarchar](255) NULL,
        '''	[Group] [nvarchar](255) NULL,
        '''	[ItemCode] [nvarchar](255) NULL,
        '''	[ItemName] [nvarchar](255) NULL,
        '''	[OldItem] [nvarchar](255) NULL,
        '''	[Revision] [nvarchar](255) NULL,
        '''	[Discipline] [nvarchar](255) NULL,
        '''	[Type] [nvarchar](255) NULL,
        '''	[Class] [nvarchar](255) NULL,
        '''	[Subcontractor] [nvarchar](2 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CreateItems() As String
            Get
                Return ResourceManager.GetString("CreateItems", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE TABLE [dbo].[getProjectPunchs(&apos;10031&apos;)](
        '''	[Area] [nvarchar](255) NULL,
        '''	[Unit] [nvarchar](255) NULL,
        '''	[Module] [nvarchar](255) NULL,
        '''	[System] [nvarchar](255) NULL,
        '''	[SubSystem] [nvarchar](255) NULL,
        '''	[Group] [nvarchar](255) NULL,
        '''	[Item] [nvarchar](255) NULL,
        '''	[ElementType] [nvarchar](255) NULL,
        '''	[ElementCode] [nvarchar](255) NULL,
        '''	[Name] [nvarchar](255) NULL,
        '''	[Discipline] [nvarchar](255) NULL,
        '''	[Type] [nvarchar](255) NULL,
        '''	[Class] [nvarchar](255) NULL,
        '''	[Subcontractor] [nvarchar](2 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CreatePunch() As String
            Get
                Return ResourceManager.GetString("CreatePunch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE TABLE [dbo].[getProjectSubsystems(&apos;10031&apos;)](
        '''	[Area] [nvarchar](255) NULL,
        '''	[Unit] [nvarchar](255) NULL,
        '''	[System] [nvarchar](255) NULL,
        '''	[SubSystem] [nvarchar](255) NULL,
        '''	[SubSystemName] [nvarchar](255) NULL,
        '''	[Description] [nvarchar](255) NULL,
        '''	[Type] [nvarchar](255) NULL,
        '''	[Priority] [float] NULL,
        '''	[Weight] [float] NULL,
        '''	[HH] [float] NULL,
        '''	[Remarks] [nvarchar](255) NULL,
        '''	[Subcontractor] [nvarchar](255) NULL,
        '''	[TargetDate] [nvarchar](255) NULL,
        '''	[PlanningDate] [nvarchar](255) NUL [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CreateSubsystem() As String
            Get
                Return ResourceManager.GetString("CreateSubsystem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE TABLE [dbo].[getProjectSystems(&apos;10031&apos;)](
        '''	[Area] [nvarchar](255) NULL,
        '''	[Unit] [nvarchar](255) NULL,
        '''	[System] [nvarchar](255) NULL,
        '''	[SystemName] [nvarchar](255) NULL,
        '''	[Description] [nvarchar](255) NULL,
        '''	[Type] [nvarchar](255) NULL,
        '''	[Priority] [float] NULL,
        '''	[Weight] [float] NULL,
        '''	[HH] [float] NULL,
        '''	[Remarks] [nvarchar](255) NULL,
        '''	[Subcontractor] [nvarchar](255) NULL,
        '''	[TargetDate] [nvarchar](255) NULL,
        '''	[PlanningDate] [nvarchar](255) NULL,
        '''	[RFCN] [nvarchar](255) NULL,
        '''	[RFCN_ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CreateSystems() As String
            Get
                Return ResourceManager.GetString("CreateSystems", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE TABLE [dbo].[getProjectTasks(&apos;10031&apos;)](
        '''	[ProjectCode] [nvarchar](255) NULL,
        '''	[Area] [nvarchar](255) NULL,
        '''	[Unit] [nvarchar](255) NULL,
        '''	[Module] [nvarchar](255) NULL,
        '''	[System] [nvarchar](255) NULL,
        '''	[SubSystem] [nvarchar](255) NULL,
        '''	[Group] [nvarchar](255) NULL,
        '''	[Item] [nvarchar](255) NULL,
        '''	[ElementType] [nvarchar](255) NULL,
        '''	[ElementCode] [nvarchar](255) NULL,
        '''	[Name] [nvarchar](255) NULL,
        '''	[Discipline] [nvarchar](255) NULL,
        '''	[Type] [nvarchar](255) NULL,
        '''	[Class] [nvarchar](255) [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CreateTask() As String
            Get
                Return ResourceManager.GetString("CreateTask", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property delete2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DeleteRed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DeleteRed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to select *
        '''from
        '''(
        '''select Area,[STATUS]
        ''',count(loopname) as Loops
        '''FROM tblInsLoop 
        '''where active=1
        '''AND [STATUS] like &apos;on%hold%&apos;
        '''and TR_Loop_Folder_QC_Release is not null and L_Done is null
        '''group by Area,[STATUS]
        '''--*********************************************************
        '''UNION ALL
        '''select Area,&apos;Index Not Signed&apos; as [STATUS]
        ''',count(loopname) as Loops
        '''FROM tblInsLoop 
        '''where active=1
        '''AND (([STATUS] not like &apos;on%hold%&apos;) or ([status] is null))
        '''and TR_Loop_Folder_QC_Release is not null and L_Done is n [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property DiffQCPrecomm() As String
            Get
                Return ResourceManager.GetString("DiffQCPrecomm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property eccables02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eccables02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT 
        '''[TBL_ID]
        ''',[tblEleCableList].Area
        ''',[EC_ID] as Tag
        ''',[EC_Type] as [Type]
        ''',[EC_Description] as [Description]
        ''',[EC_Length] as [Eng. Length]
        ''',[EC_From] as [From]
        ''',[EC_To] as [To]
        ''',vCblParProductionTotal_Vendor.Pro_Date
        ''',vCblParProductionTotal_Vendor.Percentage
        ''',[Pulled_con] as [Pulled Confirm]
        ''',[EC_Plan_Connected_Date_From] as [Connected From Date]
        ''',[EC_Plan_Connected_Date_From_con] as [Connect From Confirm]
        ''',[EC_Plan_Connected_Date_To] as [Connected To Date]
        ''',[EC_Plan_Connected_Date_To_con [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ECCableValidate() As String
            Get
                Return ResourceManager.GetString("ECCableValidate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /****** Script for SelectTopNRows command from SSMS  ******/
        '''SELECT [Area]
        '''      ,[Type]
        '''      ,[Tag]
        '''      ,[Eng Length]
        '''      ,[Partial Qnty Done]
        '''      ,[Actual Length]
        '''      ,[Percentage]
        '''      ,[Last Pulling Update]
        '''      ,[Gland To Date]
        '''      ,[Gland From Date]
        '''      ,[Connect From Date]
        '''      ,[Connect To Date]
        '''      ,[Test Date]
        '''      ,[Continuity Test Date]
        '''      ,[Qc Released Date]
        '''      ,[Pulling Subcontractor]
        '''      ,[Con 1 Subcontractor]
        '''      ,[Con 2 Subcontractor]
        '''      ,[ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property EcPro() As String
            Get
                Return ResourceManager.GetString("EcPro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EEICA_Logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EEICA Logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT
        '''[TAG]
        ''',[Type]
        ''',[Installed_Date]
        ''',[Active]
        '''FROM [tblElectricalEquipment].
        '''</summary>
        Friend ReadOnly Property EEQPro() As String
            Get
                Return ResourceManager.GetString("EEQPro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT 
        '''[TBL_ID]
        ''',Area
        ''',[TAG]
        ''',[Type]
        ''',[Type_Description]
        ''',[Des]
        ''',[Installed_Date] as [Installed Date]
        ''',[Installed_Date_con] as [Installed Date Confirm]
        ''',[Active]
        '''FROM [tblElectricalEquipment]
        '''order by Area,TAG.
        '''</summary>
        Friend ReadOnly Property EEqValidate() As String
            Get
                Return ResourceManager.GetString("EEqValidate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EICA_Blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EICA Blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EICA_Blue_Trans() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EICA Blue Trans", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EICA_Logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EICA Logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property eicaicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eicaicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property eicaicon32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eicaicon32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT
        '''tblInsLoop.Area
        ''',tblInsLoop.LoopName
        ''',Item
        ''',case when ((Item_Type is null) AND (VEICAILD01.Loop_Name is NOT null)) then &apos;Not In EICA&apos; else Item_Type end as Item_Type
        ''',replace([EICA Type],&apos;Building_FG&apos;,&apos;F&amp;G&apos;) as [EICA Type]
        ''',PO
        ''',Forecast
        ''',case when ((Available is null) and ([Pulled/Installed] is not null)) then DATEADD(day,-10,[Pulled/Installed]) else Available end as Available
        '''--,SubSystem
        ''',[Length]
        ''',[Pulled/Installed]
        ''',[Cable Con 1]
        ''',[Cable Con 2]
        ''',[Calibrated/Tested]
        ''',case when VEICA [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property EICALoopMap() As String
            Get
                Return ResourceManager.GetString("EICALoopMap", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT
        '''[TAG]
        ''',JE_Installed as [Installed Date]
        ''',[Active]
        '''FROM tblEleJunctionBox.
        '''</summary>
        Friend ReadOnly Property EJBPro() As String
            Get
                Return ResourceManager.GetString("EJBPro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT 
        '''[TBL_ID]
        ''',Area
        ''',[TAG]
        ''',JE_Type as [Type]
        ''',JE_Description as [Description]
        ''',JE_Installed as [Installed Date]
        ''',JE_Installed_con as [Installed Date Confirm]
        ''',[Active]
        '''FROM tblEleJunctionBox
        '''order by Area,TAG.
        '''</summary>
        Friend ReadOnly Property EJBValidate() As String
            Get
                Return ResourceManager.GetString("EJBValidate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property equipment32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("equipment32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property EXCEL97() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EXCEL97", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to update [HCS].[ProjectPunchs] set [SignedByTR]=replace([SignedByTR],&apos;&apos;&apos;&apos;,&apos;&apos;)
        '''update [HCS].[ProjectPunchs] set [SignedBySubcon]=replace([SignedBySubcon],&apos;&apos;&apos;&apos;,&apos;&apos;)
        '''update [HCS].[ProjectPunchs] set [SignedByClient]=replace([SignedByClient],&apos;&apos;&apos;&apos;,&apos;&apos;)
        '''
        '''update [HCS].[ProjectSubsystems] set [Data3]=replace([Data3],&apos;&apos;&apos;&apos;,&apos;&apos;)
        '''update [HCS].[ProjectSubsystems] set [Data4]=replace([Data4],&apos;&apos;&apos;&apos;,&apos;&apos;)
        '''update [HCS].[ProjectSubsystems] set [Data5]=replace([Data5],&apos;&apos;&apos;&apos;,&apos;&apos;)
        '''update [HCS].[ProjectSubsystems] set [Data6]=repla [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property FixColumnsData() As String
            Get
                Return ResourceManager.GetString("FixColumnsData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fixture32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fixture32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fixtures64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fixtures64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT &apos;Folder Signed in HCS&apos; as [Status]
        ''',CASE WHEN tblInsLoop.Submitted_to_Precom IS NULL THEN &apos;Not Submitted To Precomm&apos; else convert(nvarchar(50),format(tblInsLoop.Submitted_to_Precom,&apos;dd/MM/yyyy&apos;))
        ''' end as [Submission To Precomm Date]
        ''',Area,[LoopName],l_type as [Type],tblInsLoop.[Subsystem],tblInsLoop.[Subcontractor]
        ''',tblInsLoop.HCS_Folder_Ready as [Signed Date]
        ''',case when tblInsLoop.STATUS is null then &apos;Active&apos; else tblInsLoop.STATUS end as [Engineering Status]
        '''--,count(*) over (order by Area,tb [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property FolderSignedInHCS() As String
            Get
                Return ResourceManager.GetString("FolderSignedInHCS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT [LoopName]
        ''',case when L_Done is not null then &apos;Loop Done&apos;
        '''when Submitted_to_Precom is not null then &apos;Submitted To Precomm&apos;
        '''when HCS_Folder_Ready is not null then &apos;Folder Index Signed&apos;
        '''when TR_Loop_Folder_QC_Release is not null then &apos;QC Released&apos; 
        '''when STATUS is null then &apos;No Action&apos;
        '''else STATUS
        '''end as [Folder Location]
        '''FROM [tblInsLoop].
        '''</summary>
        Friend ReadOnly Property FolderStatus() As String
            Get
                Return ResourceManager.GetString("FolderStatus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT 
        '''[TBL_ID]
        ''',[tblInsCableList].Area
        ''',[IC_ID] as Tag
        ''',[IC_Type] as [Type]
        ''',[Sub_Type] as Subtype
        ''',[IC_Description] as [Description]
        ''',[IC_Length] as [Eng. Length]
        ''',[IC_From] as [From]
        ''',[IC_To] as [To]
        ''',vCblParProductionTotal_Vendor.Pro_Date
        ''',vCblParProductionTotal_Vendor.Percentage
        ''',[Pulled_con] as [Pulled Confirm]
        ''',[IC_Plan_Connected_Date_From] as [Connected From Date]
        ''',[IC_Plan_Connected_Date_From_con] as [Connect From Confirm]
        ''',[IC_Plan_Connected_Date_To] as [Connected To Date]
        ''',[IC_Pl [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ICCableValidate() As String
            Get
                Return ResourceManager.GetString("ICCableValidate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_marker_b_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-marker-b-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_motor_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-motor-16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_motor_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-motor-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_plug_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-plug-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_work_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-work-32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_work_321() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-work-321", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_work_94() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-work-94", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_wyoming_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-wyoming-48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT [Area]
        '''      ,[Type]
        '''      ,[Tag]
        '''      ,[Eng Length]
        '''      ,[Partial Qnty Done]
        '''      ,[Actual Length]
        '''      ,[Percentage]
        '''      ,[Last Pulling Update]
        '''      ,[Gland To Date]
        '''      ,[Gland From Date]
        '''      ,[Connect From Date]
        '''      ,[Connect To Date]
        '''      ,[Test Date]
        '''      ,[Qc Released Date]
        '''      ,[Pulling Subcontractor]
        '''      ,[Con 1 Subcontractor]
        '''      ,[Con 2 Subcontractor]
        '''      ,[Test Subcontractor]
        '''      ,[Active]
        '''  FROM vICList.
        '''</summary>
        Friend ReadOnly Property IcPro() As String
            Get
                Return ResourceManager.GetString("IcPro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT
        '''[TAG]
        ''',[Type]
        ''',[Installed_Date]
        ''',[Active]
        '''FROM [tblInsEquipment].
        '''</summary>
        Friend ReadOnly Property IEQPro() As String
            Get
                Return ResourceManager.GetString("IEQPro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT 
        '''[TBL_ID]
        ''',Area
        ''',[TAG]
        ''',[Type]
        ''',[Type_Description]
        ''',[Des]
        ''',[Installed_Date] as [Installed Date]
        ''',[Installed_Date_con] as [Installed Date Confirm]
        ''',[Active]
        '''FROM tblInsEquipment
        '''order by Area,TAG.
        '''</summary>
        Friend ReadOnly Property IEqValidate() As String
            Get
                Return ResourceManager.GetString("IEqValidate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT
        '''JunctionBox as [TAG]
        ''',Ji_Installed as [Installed Date]
        ''',[Active]
        '''FROM JunctionBox.
        '''</summary>
        Friend ReadOnly Property IJBPro() As String
            Get
                Return ResourceManager.GetString("IJBPro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT 
        '''[TBL_ID]
        ''',Area
        ''',JunctionBox as [TAG]
        ''',JI_Type as [Type]
        ''',JI_Description as [Description]
        ''',JI_Installed as [Installed Date]
        ''',JI_Installed_con as [Installed Date Confirm]
        ''',[Active]
        '''FROM JunctionBox
        '''order by Area,JunctionBox.
        '''</summary>
        Friend ReadOnly Property IJBValidate() As String
            Get
                Return ResourceManager.GetString("IJBValidate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT DISTINCT  TBLILD.LOOP_NAME
        '''FROM tblILD INNER JOIN TBLILD AS SEG ON TBLILD.Segment=SEG.Loop_Name
        '''WHERE SEG.FILENAME IS NOT NULL
        '''AND TBLILD.FILENAME IS NULL
        '''UNION ALL
        '''select distinct Loop_name from tblILD where filename is not null.
        '''</summary>
        Friend ReadOnly Property ILDWithFile() As String
            Get
                Return ResourceManager.GetString("ILDWithFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT
        '''[Instrument_Tag] as Tag
        ''',[Instrument] as [Type]
        ''',[Equipment_Name] as [For Equipment]
        ''',[Calibration_Date]
        ''',[Installation_Date]
        ''',[HookUp_Date]
        ''',[Active]
        '''FROM [tblInstruments].
        '''</summary>
        Friend ReadOnly Property InsPro() As String
            Get
                Return ResourceManager.GetString("InsPro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property inst32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("inst32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT 
        '''[TBL_ID]
        ''',[Area]
        ''',[Instrument_Tag] as Tag
        ''',[Furnished_By] as [Furnished By]
        ''',case when [Instrument] = &apos;instrument&apos; then &apos;Device&apos;
        '''when [Instrument] is null then &apos;Accessory&apos; else [Instrument] end as [Type]
        ''',[Instrument_Type_Desc] as [Description]
        ''',[Equipment_Name] as [Equipment Name]
        ''',case when [Calibration_Type] =&apos;no&apos; then &apos;N/A&apos; else &apos;Yes&apos; end as [Calibration Scope]
        ''',[Calibration_Date] as [Calibration Date]
        ''',[Calibration_Date_co] as [Calibration Date Confirm]
        ''',[Installation_Date] as [Inst [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property InsValidate() As String
            Get
                Return ResourceManager.GetString("InsValidate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Loginbackground() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Loginbackground", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LoginbackgroundTrans2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LoginbackgroundTrans2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logo1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to select
        '''vLog.Discipline,vLog.Tag,vLog.Step_Name as [Action],vLog.uname as [User Name]
        ''',vLog.udate as [Date]
        ''',case when vLog.uvalue =&apos;1&apos; then &apos;Accept&apos;
        '''when vLog.uvalue =&apos;0&apos; then &apos;Reject&apos;
        '''when vLog.uvalue is null then &apos;Deleted&apos;
        '''else vLog.uvalue end as [New Update]
        '''from (
        '''select &apos;Electrical Cable&apos; as Discipline,tblEleCableList_Log.* from tblEleCableList_Log
        '''UNION ALL
        '''select &apos;Electrical Equipment&apos; as Discipline,tblElectricalEquipment_Log.* from tblElectricalEquipment_Log
        '''UNION ALL
        '''select &apos;Instrument  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Logs() As String
            Get
                Return ResourceManager.GetString("Logs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT DISTINCT
        '''tblInsLoop.Subsystem,tblInsLoop.Area,tblInsLoop.Active
        ''',tblInsLoop.Planning_START_Date AS [Plan Start Date], tblInsLoop.Planning_FINISH_Date AS [Plane Finish Date], tblInsLoop.LoopPriority AS [Priority]
        ''',tblInsLoop.LoopName
        ''',VILDMAP.Area as [Item Area]
        ''',case when VILDMAP.Discipline is null then &apos;No ILD&apos; else VILDMAP.Discipline end as Discipline
        ''',VILDMAP.Type,VILDMAP.Item,VILDMAP.SubSystem AS [Item Subsystem],VILDMAP.Forecast,VILDMAP.Available
        ''',VILDMAP.[Pulled/Installed],VILDMAP.[Cable [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Loop_Map() As String
            Get
                Return ResourceManager.GetString("Loop_Map", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property loop32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loop32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT 
        '''[TBL_ID],[Subsystem],[Area],[Subcontractor]
        ''',[L_Type] as [Type]
        ''',[LoopName]
        ''',[L_Description] as [Description]
        ''',[L_Done] as [Precomm Done Date]
        ''',[STATUS] as [Constraint]
        ''',[Constraints] as [Constraints Description]
        ''',[Active]
        '''FROM [tblInsLoop].
        '''</summary>
        Friend ReadOnly Property LoopBasicInfo() As String
            Get
                Return ResourceManager.GetString("LoopBasicInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Declare @Unit nvarchar(50)
        '''select @unit=&apos;u01&apos;
        '''
        '''select
        '''Area
        '''--,count(loopname) as Scope
        ''',count(l_done) as Done
        ''',format(min(l_done),&apos;dd/MM/yyyy&apos;) as [Start Shoot]
        ''',format(max(l_done),&apos;dd/MM/yyyy&apos;) as [Last Shoot]
        ''',datediff(day,min(l_done),max(l_done)) as [Dur(Day)]
        ''',case when convert(float,datediff(day,min(l_done),max(l_done))) =0 then null
        '''else
        '''round(convert(float,count(l_done)) / convert(float,datediff(day,min(l_done),max(l_done))),2) 
        '''end as [Avg(Day)]
        '''--,sum(case when l_done is null and STAT [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property LoopCalculationSummary() As String
            Get
                Return ResourceManager.GetString("LoopCalculationSummary", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT &apos;No RFI&apos; as Remark,[Unit],[Loop Name],[Type],[Folder Preparation],tblInsLoop.[Subsystem],tblInsLoop.[Subcontractor]
        ''',tblInsLoop.STATUS,tblInsLoop.L_Constr_Release as [Const Comp Date]
        '''FROM [tblILDFB] with (nolock)
        '''inner join tblInsLoop
        '''on [tblILDFB].[Loop Name]=tblInsLoop.LoopName
        '''where [Const. Completed]=1
        '''and [HCS. Completed]&lt;&gt;1
        '''and tblInsLoop.HCS_Folder_Ready is null
        '''and tblInsLoop.Active=1
        '''and tblInsLoop.STATUS is null
        '''order by unit.
        '''</summary>
        Friend ReadOnly Property LoopConsFinishedNoRFI() As String
            Get
                Return ResourceManager.GetString("LoopConsFinishedNoRFI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT 
        '''case when [TREICAKNPC].[dbo].[tblInsLoop].LoopName is null then &apos;New HCS Loop&apos; 
        '''     when [HCS10031_PLANNING].[dbo].[getProjectGroups(&apos;10031&apos;)].GroupID IS NULL then &apos;Deactivated Loop in HCS&apos;
        '''	 when [HCS10031_PLANNING].[dbo].[getProjectGroups(&apos;10031&apos;)].Active=1 and [TREICAKNPC].[dbo].[tblInsLoop].Active=0 then &apos;Deactivated In EICA And Active In HCS&apos;
        '''	 when [TREICAKNPC].[dbo].[tblInsLoop].Subsystem &lt;&gt; [HCS10031_PLANNING].[dbo].[getProjectGroups(&apos;10031&apos;)].[SubSystem] collate Latin1_General_100_CI_A [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property LoopHCSEICA() As String
            Get
                Return ResourceManager.GetString("LoopHCSEICA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF OBJECT_ID(&apos;tempdb..#Loop&apos;) IS NOT NULL
        '''DROP TABLE #Loop
        '''Create table #Loop
        '''(
        '''Loop_Name nvarchar (50)
        ''',Discipline nvarchar (50)
        ''',Item_Type nvarchar (50)
        ''',Scope float
        ''',[Conn Scope] float
        ''',Available float
        ''',Done float
        ''',Connected float
        ''',[Calibrated/Tested] float
        ''',[Hookup Scope] float null
        ''',Hookup float
        ''',[QC Released] float
        ''')
        '''insert into #Loop
        '''Select
        '''Loop_Name,Discipline,Item_Type,Scope,[Conn Scope],Available,Done,Connected,[Calibrated/Tested],[Hookup Scope],Hookup,[QC Released]
        '''FROM
        '''(
        '''se [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property LoopJobCard() As String
            Get
                Return ResourceManager.GetString("LoopJobCard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to select Area
        ''',case when datediff(day,getdate(),max(tblInsLoop.Planning_FINISH_Date))&lt;0 then 0 else 
        ''' datediff(day,getdate(),max(tblInsLoop.Planning_FINISH_Date))
        ''' end as [Remaining Days]
        '''from tblInsLoop
        '''group by area
        '''order by area.
        '''</summary>
        Friend ReadOnly Property LoopRemainigDays() As String
            Get
                Return ResourceManager.GetString("LoopRemainigDays", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT [tbl_id] as ID,[tblConstraints].cons_name as [Constraint],tblDepartments.dep_name as [Department],[issued_date] as [Issued Date],[action_by] as [Action By]
        ''',[forecast_released_date] as [Forecast Date],[released_date] as [Released Date],[Remarks]
        '''FROM [tblLoopConstraint]
        '''inner join tblDepartments on [tblLoopConstraint].dep_id = tblDepartments.dep_id
        '''inner join [tblConstraints] on [tblLoopConstraint].cons_id = [tblConstraints].cons_id.
        '''</summary>
        Friend ReadOnly Property LoopsCons() As String
            Get
                Return ResourceManager.GetString("LoopsCons", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to select *
        '''from
        '''(
        '''Select 
        '''Area
        ''',[Activity Name]
        ''',Done,Type,Unit
        '''FROM
        '''(
        '''---Loop DONE
        '''select Area,
        '''&apos;Loop&apos; as [Activity Name]
        ''',count([L_Done]) as &apos;Done&apos;,&apos;Loop Test&apos; as [Type],&apos;Each&apos; as [Unit] FROM tblInsLoop where active=1
        '''group by Area
        '''--*********************************************************
        '''UNION ALL
        '''---SUBMIT TO PRECOMM
        '''select Area,
        '''&apos;Loop&apos; as [Activity Name]
        ''',count([Submitted_to_Precom]) as &apos;Done&apos;,&apos;Submitted_to_Precom&apos; as [Type],&apos;Each&apos; as [Unit] FROM tblInsLoop where active=1
        '''group by A [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property LoopsSteps() As String
            Get
                Return ResourceManager.GetString("LoopsSteps", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT &apos;RFI Ready in HCS Without Index&apos; as Remark,Area as [Unit],[LoopName] as [Loop Name],tblInsLoop.[Subsystem],tblInsLoop.[Subcontractor]
        ''',tblInsLoop.TR_Loop_Folder_QC_Release as [Workfront Release Date]
        '''FROM tblInsLoop
        '''where TR_Loop_Folder_QC_Release IS NOT NULL
        '''and tblInsLoop.Active=1
        '''and tblInsLoop.STATUS is null
        '''and tblInsLoop.HCS_Folder_Ready is null
        '''order by Area.
        '''</summary>
        Friend ReadOnly Property LoopWorkfront() As String
            Get
                Return ResourceManager.GetString("LoopWorkfront", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ok_svgrepo_com() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ok-svgrepo-com", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to select
        '''[tblActIDS].[ActName],[tblActIDS].[EICA_Area]
        ''',vEQ.*
        '''FROM
        '''(
        '''SELECT &apos;Ele&apos; as Discipline,[TAG],[Type],[Type_Description]
        ''',IC_Plan_P6_ActID_Install
        ''',ForeCast_Date,Arrived_Date
        ''',[Planned_Finished_Date]
        ''',[Actual_Forecast_Date]
        '''FROM [tblElectricalEquipment]
        '''where [Actual_Forecast_Date] &lt;= getdate()
        '''and Installed_Date is null and active=1
        '''UNION
        '''SELECT &apos;Ins&apos; as Discipline,[TAG],[Type],[Type_Description]
        ''',IC_Plan_P6_ActID_Install
        ''',ForeCast_Date,Arrived_Date
        ''',[Planned_Finished_Date]
        ''',[Actual_ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property OldPlanningForecast() As String
            Get
                Return ResourceManager.GetString("OldPlanningForecast", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to declare @result as nvarchar(max)
        '''set @result = &apos;
        '''
        '''SELECT [PCSXXX].[dbo].[ActivityBudget].[Actid]
        '''      ,[PCSXXX].[dbo].[ActivityBudget].[ResID]
        '''      ,[PCSXXX].[dbo].[ActivityBudget].[BaseLine] -- Filter by the current baseline
        '''      ,[PCSXXX].[dbo].[ActivityBudget].[Budget] -- Qty
        '''      ,[PCSXXX].[dbo].[ActivityBudget].[Active]
        ''',[BDResDistribAct].* 
        '''  FROM [PCSXXX].[dbo].[ActivityBudget]
        '''  inner join [PCSXXX].[dbo].[BDResDistribAct]
        '''  on [PCSXXX].[dbo].[ActivityBudget].actid= [PCSXXX].[dbo].[BDR [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PCSDone() As String
            Get
                Return ResourceManager.GetString("PCSDone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to select distinct
        '''vmap.[Item Area]
        ''',vmap.[Discipline]
        ''',vmap.[Type]
        ''',vmap.[Item]
        ''',vmap.[Item Subsystem]
        ''',vmap.[Forecast]
        ''',vmap.[Available]
        ''',vmap.[Pulled/Installed]
        ''',vmap.[Cable Con 1]
        ''',vmap.[Cable Con 2]
        ''',vmap.[Calibrated/Tested]
        ''',vmap.[QC/HCS Released]
        '''
        '''from
        '''(
        '''SELECT 
        '''tblInsLoop.Subsystem,tblInsLoop.Area,tblInsLoop.LoopName
        ''',VILDMAP.Area as [Item Area]
        ''',case when VILDMAP.Discipline is null then &apos;No ILD&apos; else VILDMAP.Discipline end as Discipline
        ''',VILDMAP.Type,VILDMAP.Item,VILDMAP.SubSystem  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PendingItemsNotInHCS() As String
            Get
                Return ResourceManager.GetString("PendingItemsNotInHCS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF OBJECT_ID(&apos;tempdb..#LoopMAP&apos;) IS NOT NULL
        '''DROP TABLE #LoopMAP
        '''Create table #LoopMAP
        '''(
        '''Subsystem NVARCHAR (50)
        ''',Area NVARCHAR (50)
        ''',LoopName NVARCHAR (50)
        ''',[Item Area] NVARCHAR (50)
        ''',Discipline NVARCHAR (50)
        ''',[Type] NVARCHAR (50)
        ''',Item NVARCHAR (50)
        ''',[Item Subsystem] NVARCHAR (50)
        ''',Forecast NVARCHAR (50)
        ''',Available NVARCHAR (50)
        ''',[Pulled/Installed] NVARCHAR (50)
        ''',[Cable Con 1] NVARCHAR (50)
        ''',[Cable Con 2] NVARCHAR (50)
        ''',[Calibrated/Tested] NVARCHAR (50)
        ''',[QC/HCS Released] NVARCHAR (50)
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PendingLoopItems() As String
            Get
                Return ResourceManager.GetString("PendingLoopItems", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property trays32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("trays32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TRUNCATE TABLE [HCS].ProjectElements
        '''TRUNCATE TABLE [HCS].ProjectGroups
        '''TRUNCATE TABLE [HCS].ProjectItems
        '''TRUNCATE TABLE [HCS].ProjectPunchs
        '''TRUNCATE TABLE [HCS].ProjectSubsystems
        '''TRUNCATE TABLE [HCS].ProjectSystems
        '''TRUNCATE TABLE [HCS].ProjectTasks
        '''
        '''ALTER TABLE [HCS].[ProjectPunchs] ALTER column [SignedByTR] NVARCHAR(100)
        '''ALTER TABLE [HCS].[ProjectPunchs] ALTER column [SignedBySubcon] NVARCHAR(100)
        '''ALTER TABLE [HCS].[ProjectPunchs] ALTER column [SignedByClient] NVARCHAR(100)
        '''
        '''ALTER TABLE [HCS]. [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property TruncateHCSs() As String
            Get
                Return ResourceManager.GetString("TruncateHCSs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to update v
        '''set v.Active=0
        '''from
        '''(
        '''SELECT 
        '''case when [TREICAKNPC].[dbo].[tblInsLoop].LoopName is null then &apos;New HCS Loop&apos; 
        '''     when [HCS10031_PLANNING].[dbo].[getProjectGroups(&apos;10031&apos;)].GroupID IS NULL then &apos;Deactivated Loop in HCS&apos;
        '''	 ELSE &apos;No Remark&apos;
        '''	end as Remark
        ''',[HCS10031_PLANNING].[dbo].[getProjectGroups(&apos;10031&apos;)].[Area],[Unit],[System],[HCS10031_PLANNING].[dbo].[getProjectGroups(&apos;10031&apos;)].[SubSystem],GroupID,[Type]
        ''',[HCS10031_PLANNING].[dbo].[getProjectGroups(&apos;10031&apos;)].[Subcontractor]
        ''',[TREIC [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property UpdateDeactivatedLoopInHCS() As String
            Get
                Return ResourceManager.GetString("UpdateDeactivatedLoopInHCS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to --UPDATE INS INSTALLATION
        '''UPDATE V
        '''SET V.Installation_Date=V.update_date
        '''FROM
        '''(
        '''SELECT 
        '''[item_type],[tag],[ms_1],[ms_2],[ms_3],[update_user],[update_date],[update_err],[reported_by],[ms_4]
        ''',tblInstruments.Installation_Date
        '''FROM [tbl_Update_MileStone] WITH (NOLOCK)
        '''INNER JOIN tblInstruments WITH (NOLOCK)
        '''ON [tbl_Update_MileStone].TAG=tblInstruments.Instrument_Tag
        '''WHERE [tbl_Update_MileStone].item_type=21
        '''AND tblInstruments.Installation_Date IS NULL
        ''') AS V
        '''--------------------------------------- [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property UpdateEICA() As String
            Get
                Return ResourceManager.GetString("UpdateEICA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to update v
        '''set HCS_Folder_Ready=[SignedByTR]
        '''FROM
        '''(
        '''SELECT 
        '''HCS10031_PLANNING..[getProjectTasks(&apos;10031&apos;)].SubSystem
        ''',HCS10031_PLANNING..[getProjectTasks(&apos;10031&apos;)].Unit
        ''',HCS10031_PLANNING..[getProjectTasks(&apos;10031&apos;)].DocName
        ''',HCS10031_PLANNING..[getProjectTasks(&apos;10031&apos;)].[Group]
        ''',TREICAKNPC..tblinsloop.LoopName
        ''',TREICAKNPC..tblinsloop.HCS_Folder_Ready
        ''',convert(date,HCS10031_PLANNING.[dbo].[getProjectTasks(&apos;10031&apos;)].[SignedByTR]) as [SignedByTR]
        '''FROM HCS10031_PLANNING.[dbo].[getProjectTasks(&apos;10031&apos;)] [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property UpdateIndexDone() As String
            Get
                Return ResourceManager.GetString("UpdateIndexDone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to WITH ILD
        '''AS
        '''(
        '''SELECT DISTINCT 
        '''[Loop_Name],[Loop_Type]
        '''FROM [tblILD]
        '''WHERE Loop_Type IS NOT NULL
        ''')
        '''UPDATE V
        '''SET L_Description=Loop_Type
        '''FROM
        '''(
        '''SELECT 
        '''ILD.Loop_Type
        ''',tblInsLoop.LoopName,tblInsLoop.L_Description
        '''FROM ILD
        '''INNER JOIN tblInsLoop
        '''ON ILD.Loop_Name=tblInsLoop.LoopName
        ''') AS V.
        '''</summary>
        Friend ReadOnly Property UpdateLoopDescription() As String
            Get
                Return ResourceManager.GetString("UpdateLoopDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to update v
        '''set v.[EICA Loop Subcontractor]=v.Subcontractor
        ''',v.[EICA Loop Subsystem]=v.SubSystem
        '''from
        '''(
        '''SELECT 
        '''case when [TREICAKNPC].[dbo].[tblInsLoop].LoopName is null then &apos;New HCS Loop&apos; 
        '''     when [HCS10031_PLANNING].[dbo].[getProjectGroups(&apos;10031&apos;)].GroupID IS NULL then &apos;Deactivated Loop in HCS&apos;
        '''	 when [HCS10031_PLANNING].[dbo].[getProjectGroups(&apos;10031&apos;)].Active=1 and [TREICAKNPC].[dbo].[tblInsLoop].Active=0 then &apos;Deactivated In EICA And Active In HCS&apos;
        '''	 when [TREICAKNPC].[dbo].[tblInsLoop].Subs [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property UpdateLoopInfoFromHCS() As String
            Get
                Return ResourceManager.GetString("UpdateLoopInfoFromHCS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPDATE V
        '''SET [Planning_FINISH_Date]=TargetDate
        '''FROM
        '''(
        '''SELECT [TBL_ID]
        '''      ,[LoopName],[Planning_FINISH_Date],[tblInsLoop].Subsystem
        '''   ,HCS.SubSystem AS [HCS SUBSYSTEM],HCS.TargetDate
        '''  FROM [TREICAKNPC].[dbo].[tblInsLoop]
        '''  INNER JOIN [HCS10031_PLANNING].[dbo].[getProjectSubsystems(&apos;10031&apos;)] AS HCS
        '''  ON [tblInsLoop].Subsystem=HCS.SubSystem COLLATE Latin1_General_100_CI_AS
        '''  ) AS V.
        '''</summary>
        Friend ReadOnly Property UpdateLoopTargetDate() As String
            Get
                Return ResourceManager.GetString("UpdateLoopTargetDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to update v
        '''set Submitted_For_Certificate=SignedByClient
        '''FROM
        '''(
        '''SELECT 
        '''HCS10031_PLANNING..[getProjectTasks(&apos;10031&apos;)].SubSystem
        ''',HCS10031_PLANNING..[getProjectTasks(&apos;10031&apos;)].Unit
        ''',HCS10031_PLANNING..[getProjectTasks(&apos;10031&apos;)].DocName
        ''',HCS10031_PLANNING..[getProjectTasks(&apos;10031&apos;)].[Group]
        ''',TREICAKNPC..tblinsloop.LoopName
        ''',TREICAKNPC..tblinsloop.Submitted_For_Certificate
        ''',convert(date,HCS10031_PLANNING.[dbo].[getProjectTasks(&apos;10031&apos;)].SignedByClient) as SignedByClient
        '''FROM HCS10031_PLANNING.[dbo].[g [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property UpdateSubmitForCert() As String
            Get
                Return ResourceManager.GetString("UpdateSubmitForCert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to update tblild
        '''
        '''set Loop_Name=REPLACE(loop_name, &apos; &apos;,&apos;&apos;)
        '''
        '''GO
        '''
        '''--Ins Cable
        '''UPDATE v
        '''
        '''set [Item_Type]= &apos;IC: &apos; + IC_Type
        '''
        '''FROM
        '''
        '''(
        '''
        '''Select [tblILD].[tbl_id],[Loop_Name],[Item],[Item_Type],
        '''
        '''tblInsCableList.IC_Type
        '''
        '''from tblILD
        '''
        '''INNER JOIN tblInsCableList
        '''
        '''on [tblILD].[Item]=tblInsCableList.IC_ID
        '''
        '''where [tblILD]. Item_Type IS NULL
        '''
        '''
        ''')as V
        '''
        '''GO
        '''
        '''
        '''
        '''UPDATE v
        '''
        '''set [Item_Type]= &apos;EC: &apos; + EC_Type
        '''
        '''FROM
        '''
        '''(
        '''
        '''Select [tblILD].[tbl_id],[Loop_Name],[Item],[Item_Type],
        '''
        '''tblEleCableLis [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ValidiateILD() As String
            Get
                Return ResourceManager.GetString("ValidiateILD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property wire() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wire", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property wire2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wire2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property wire32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wire32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
