Public Class Enumerations

    Public Enum UpdateType
        ADDNEW = 1
        UPDATEPROGRESS = 2
        UPDATEDATA = 3
        UPDATELOOPFOLDERDONE = 4
        UPDATELOOPPRINTED = 5
        UPDATELOOPQCRELEASED = 6
        UPDATELOOPFOLDERREADY = 7
        UPDATELOOPFOLDERSUBMITTEDTPPRECOMM = 8
        UPDATELOOPFOLDERAPPROVED = 9
        UPDATELOOPFOLDESUBMITTOQC = 10
        UPDATELOOPFOLDERRETURNFROMQC = 11
        UPDATELOOPFOLDERCONSRELEASE = 20
        UPDATELOOPFOLDERCONSTARGET = 22
        UPDATELOOPFOLDERFAILED = 23
        CLEARLOOPFOLDERDONE = 12
        CLEARLOOPPRINTED = 13
        CLEARLOOPQCRELEASED = 14
        CLEARLOOPFOLDERREADY = 15
        CLEARLOOPFOLDERSUBMITTEDTPPRECOMM = 16
        CLEARLOOPFOLDERAPPROVED = 17
        CLEARLOOPFOLDESUBMITTOQC = 18
        CLEARLOOPFOLDERRETURNFROMQC = 19
        CLEARLOOPFOLDERCONSRELEASE = 21
        CLEARLOOPFOLDERCONSTARGET = 24
        CLEARLOOPFOLDERFAILED = 25
    End Enum


End Class
